name: ImranKhan
favicon: null
layout_spectrum: 0.54829
typography_spectrum: 0.56265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f67428'
    - '#ffffff'
    - '#000000'
    - '#841619'
    - '#007cb7'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
